repos:
- repo: local
  hooks:
  - id: go-coverage-test
    name: go coverage test
    entry: go-coverage-test
    types:
    - go
    language: script
    description: Run go coverage test
    pass_filenames: false
    args: [--settings-file=.go-coverage-test-settings]  # Specify the path to the SETTINGS_FILE
