#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx nx affected -t test && npx nx affected -t component-test && npx nx lint component-ui && npx nx lint frontend-template && nx test frontend-template && nx test backend-template
